Jack Weyer
github: jackweyer
USC ID: 5835915208

4. Pandas

In [1]:
import pandas as pd

In [48]:
Sal = pd.read_csv("Salaries.csv") #read data

yearID teamID lgID   playerID    salary
0        1985    ATL   NL  bedrost01    550000
1        1985    ATL   NL  benedbr01    545000
2        1985    ATL   NL   campri01    633333
3        1985    ATL   NL  ceronri01    625000
4        1985    ATL   NL  chambch01    800000
...       ...    ...  ...        ...       ...
25569    2015    WAS   NL  treinbl01    512800
25570    2015    WAS   NL  ugglada01    507500
25571    2015    WAS   NL  werthja01  21000000
25572    2015    WAS   NL  zimmejo02  16500000
25573    2015    WAS   NL  zimmery01  14000000

[25574 rows x 5 columns]

Make the column playerID in the csv file as the index column and the first row
as the header. Also, skip the second row when reading the file

In [53]:
Sal = Sal.iloc[1:].reset_index(drop = True)
Sal = Sal.set_index("playerID")

Select the id of the players who are registered in ATL and HOU whose salary is
higher than one million.

In [63]:
Sal = Sal[((Sal.teamID == "ATL") | (Sal.teamID == "HOU")) & (Sal.salary > 1000000)]

In [ ]:
Use the describe() method to calculate the standard deviation, first quartile, me-
dian, third quartile, mean, maximum, and minimum of the salary in team ATL.

In [69]:
Sal[(Sal.teamID == "ATL")].salary.describe()

count    3.250000e+02
mean     5.324481e+06
std      4.083713e+06
min      1.025000e+06
25%      2.000000e+06
50%      3.850000e+06
75%      7.666667e+06
max      1.606180e+07
Name: salary, dtype: float64

Create a Python dictionary object whose keys are the headers of the dataframe
created in the read_csv() exercise and values are Python list objects that contain data corresponding to the headers. (Here, use the iterrows() method to iterate each row of the dataframe and copy it to a dictionary. However, there is an easier way. Learn how the to_dict() method works by yourself later)

In [92]:
Sal_dict = {}
yearIDs = []
teamIDs = []
lgIDs = []
salaries = []

In [93]:
for index, row in Sal.iterrows():
    yearIDs.append(row["yearID"])
    teamIDs.append(row["teamID"])
    lgIDs.append(row["lgID"])
    salaries.append(row["salary"])

In [94]:
Sal_dict["teamID"] = teamIDs
Sal_dict["yearID"] = yearIDs
Sal_dict["lgID"] = lgIDs
Sal_dict["salary"] = salaries

Create a dataframe using pd.DataFrameRead and from
the dictionary created in (e). Then, change the header to "a", "b", "c", ... 

In [99]:
new_df = pd.DataFrame(Sal_dict)
new_df.columns = ["a", "b", "c", "d"]

In [100]:
new_df

a     b   c        d
0    ATL  1985  NL  1500000
1    ATL  1985  NL  1625000
2    ATL  1985  NL  1354167
3    HOU  1985  NL  1350000
4    ATL  1986  NL  1800000
..   ...   ...  ..      ...
590  HOU  2015  AL  3000000
591  HOU  2015  AL  8000000
592  HOU  2015  AL  2000000
593  HOU  2015  AL  2400000
594  HOU  2015  AL  4200000

[595 rows x 4 columns]

5. Numpy

In [104]:
import numpy as np

Create a 2-dimensional Python list object, then convert it to a Numpy array
object.

In [101]:
list = [[17]*4]*4

In [108]:
array = np.array(list)
array

array([[17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17]])

Examine the ndim, shape, size, dtype, itemsize, and data attributes of the numpy array object. Make sure you understand their functions

In [116]:
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)
print(array.itemsize)
print(array.data)

2
(4, 4)
16
int32
4


Learn the dimension concept of an ndarray object by using reshape() and flatten() methods

In [128]:
print(np.arange(16).reshape(8,2))
flat = array.flatten()

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


Understand how the slice operation works for 1-D arrays and 2-D arrays and
practice by yourself.

In [130]:
print(flat[:4])
print(array[1, 1:3])

[17 17 17 17]
[17 17]


Learn operations on ndarray by examining the argmin(), argmax(), min(), max(),
mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), and mod()
methods. Make yourself comfortable with these methods.

In [168]:
print(flat.argmin())
print(array.argmax())
print(array.min())
print(array.max())
print(array.mean())
print(array.sum())
print(array.std())
#print(np.dot(array))
print(np.square(array))
print(np.sqrt(16))
abs(array)

0
0
17
17
17.0
272
0.0


TypeError: dot() missing 1 required positional argument: 'b'

Examine the arange(), ones(), zeros(), eye(), linspace(), and concatenate() methods. Make yourself comfortable with these methods.

In [161]:
print(np.arange(16))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [178]:
print(np.ones(5))
print(np.zeros(5))
print(np.eye(5))
time = np.linspace(20, 145,5)
np.concatenate(#array1, #array2, #axis=_)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


TypeError: dispatcher for __array_function__ did not return an iterable

In [175]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

6. Scikit-Learn